name: 'AWS Codebuild Async Trigger'
description: 'Execute CodeBuild::startBuild for the current repo.'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  project-name:
    description: 'AWS CodeBuild Project Name'
    required: true
  buildspec-override:
    description: 'Buildspec Override'
    required: false
  env-vars-for-codebuild:
    description: 'Comma separated list of environment variables to send to CodeBuild'
    required: false
outputs:
  aws-build-id:
    description: 'The AWS CodeBuild Build ID for this build.'
runs:
  using: 'node12'
  main: 'dist/index.js'
